# Generated by Django 5.1.6 on 2025-03-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
            ],
            options={
                'permissions': [('can_view', 'Can view book details'), ('can_create', 'Can add a new book'), ('can_edit', 'Can edit book details'), ('can_delete', 'Can delete a book')],
            },
        ),
    ]
