<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-12 16:16
=======
# Generated by Django 5.1.6 on 2025-02-14 20:29
>>>>>>> 322e5fd575c4677913c3bed629c19f9a742cb34f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
            ],
        ),
    ]
